#!/bin/bash

# Help script for Launcher Hub development

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

clear
echo -e "${BLUE}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         ${CYAN}🚀 Launcher Hub Development Guide${BLUE}            ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${GREEN}📋 Quick Start${NC}"
echo "═══════════════"
echo "1. Configure environment:  ${YELLOW}./scripts/configure-env.sh${NC}"
echo "2. Test connection:        ${YELLOW}./scripts/test-connection.sh${NC}"
echo "3. Deploy plugin:          ${YELLOW}./scripts/deploy-simple.sh${NC}"
echo "4. View logs:              ${YELLOW}./scripts/view-logs.sh${NC}"
echo ""

echo -e "${GREEN}🛠️  Available Scripts${NC}"
echo "═════════════════════"
echo -e "${CYAN}Setup & Configuration:${NC}"
echo "  configure-env.sh    - Set Steam Deck IP and create .env"
echo "  setup-deck-dev.sh   - Prepare Steam Deck for development"
echo ""
echo -e "${CYAN}Development:${NC}"
echo "  deploy-simple.sh    - Deploy plugin to Steam Deck"
echo "  test-connection.sh  - Test SSH connection"
echo "  view-logs.sh        - View live plugin logs"
echo "  bump-version.sh     - Update version numbers"
echo ""

echo -e "${GREEN}🎮 VSCode Tasks${NC}"
echo "═════════════════"
echo "Press ${CYAN}Ctrl+Shift+P${NC} and type 'Run Task' to see all tasks:"
echo ""
echo "  ${CYAN}Primary Workflow:${NC}"
echo "  • 🧹 Clean, Build & Deploy - Full development cycle"
echo "  • 📦 Build & Deploy        - Build and deploy"
echo "  • 🚀 Deploy Only           - Quick deployment"
echo ""
echo "  ${CYAN}Development:${NC}"
echo "  • 👀 Watch Mode            - Auto-rebuild on changes"
echo "  • ✅ Fix Code Issues       - Lint and format"
echo "  • 🔌 Test Connection       - Check Steam Deck SSH"
echo "  • 📋 View Plugin Logs      - Live log monitoring"
echo ""

echo -e "${GREEN}📁 Project Structure${NC}"
echo "═════════════════════"
echo "  dist/index.js      - Frontend plugin (JavaScript)"
echo "  main.py            - Backend plugin (Python)"
echo "  plugin.json        - Plugin metadata"
echo "  package.json       - Node.js configuration"
echo "  .env               - Environment configuration"
echo ""

echo -e "${GREEN}🔧 Make Commands${NC}"
echo "══════════════════"
echo "  ${YELLOW}make setup${NC}         - Initial project setup"
echo "  ${YELLOW}make package${NC}       - Build plugin"
echo "  ${YELLOW}make deploy${NC}        - Deploy to Steam Deck"
echo "  ${YELLOW}make clean${NC}         - Remove build artifacts"
echo "  ${YELLOW}make verify${NC}        - Check project structure"
echo "  ${YELLOW}make help${NC}          - Show make targets"
echo ""

echo -e "${GREEN}📍 Steam Deck Setup${NC}"
echo "════════════════════"
echo "1. Enable SSH on Steam Deck:"
echo "   • Switch to Desktop Mode"
echo "   • Open Konsole terminal"
echo "   • Set password: ${CYAN}passwd deck${NC}"
echo "   • Enable SSH: ${CYAN}sudo systemctl enable sshd${NC}"
echo "   • Start SSH: ${CYAN}sudo systemctl start sshd${NC}"
echo ""
echo "2. Find Steam Deck IP:"
echo "   • Desktop Mode > System Settings > Network"
echo "   • Look for IP address (e.g., 192.168.1.100)"
echo ""
echo "3. Install Decky Loader:"
echo "   • Visit: ${CYAN}https://decky.xyz${NC}"
echo "   • Follow installation instructions"
echo ""

echo -e "${GREEN}❓ Common Issues${NC}"
echo "══════════════════"
echo "• ${YELLOW}Can't connect to Steam Deck?${NC}"
echo "  - Check IP in .env matches Steam Deck"
echo "  - Ensure SSH is enabled and running"
echo "  - Verify same network connection"
echo ""
echo "• ${YELLOW}Plugin not showing in UI?${NC}"
echo "  - Check logs: ./scripts/view-logs.sh"
echo "  - Verify Decky Loader is installed"
echo "  - Try restarting Steam Deck UI"
echo ""
echo "• ${YELLOW}Permission denied errors?${NC}"
echo "  - Plugin directories are owned by root (by design)"
echo "  - Use deploy scripts which handle permissions"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
echo -e "Documentation: ${CYAN}CLAUDE.md${NC}"
echo -e "Issues: ${CYAN}https://github.com/yourusername/launcher-hub${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"